# Generated by Django 5.0.6 on 2024-07-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_requestlog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='method',
            field=models.CharField(default=None, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='username',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
