# Generated by Django 5.0.6 on 2024-07-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_requestlog_method_alter_requestlog_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('manager', 'Manager'), ('customer', 'Customer')], default='manager', max_length=10),
        ),
    ]
